@startuml
entity hospital {
    id : UUID PRIMARY KEY
    name : VARCHAR (255) NOT NULL
    max_capacity : SMALLINT NOT NULL
    lat : VARCHAR (255)
    long : VARCHAR (255)
}


entity department {
    id: UUID PRIMARY KEY
    name: VARCHAR (255) NOT NULL
    --
    hospital_id : FK hospital.id NOT NULL
}

entity station {
    id : UUID PRIMARY KEY
    name : VARCHAR (255) NOT NULL
    --
    department_id : FK department.id NOT NULL
    station_type_id : FK station_type.id NOT NULL
}

entity station_type {
    id : UUID PRIMARY KEY
    name : VARCHAR (255) NOT NULL
    --
    station_type_unique_name: UNIQUE(name)
}

entity bed {
    id : UUID PRIMARY KEY
    name: VARCHAR (255) NOT NULL
    state_last_changed : BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000
    --
    type : FK bed_type.id
    state : FK bed_state.id
    station_id : FK station.id
}

entity bed_type {
    id : UUID PRIMARY KEY
    name : VARCHAR (255) NOT NULL
    --
    bed_type_unique_name: UNIQUE(name)
    --
    bed_type_idx_name: INDEX(name)
}

entity bed_state {
    id : UUID PRIMARY KEY
    name : VARCHAR (255) NOT NULL
    --
    bed_state_unique_name: UNIQUE(name)
    --
    bed_state_idx_name: UNIQUE(name)
}

hospital --|{ station
station }|-- station_type
station --|{ bed
bed }|-- bed_type
bed }|-- bed_state
@enduml